{% set version = "0.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggstats
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggstats_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggstats/ggstats_{{ version }}.tar.gz
  sha256: dd7ca086472adccc2e5ac222ef8fdcb01fade957b851bc2ec0cd6a03af480fc2

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-broom.helpers
    - r-cli
    - r-dplyr
    - r-forcats
    - r-ggplot2
    - r-lifecycle
    - r-magrittr
    - r-scales
    - r-tidyr
  run:
    - r-base
    - r-broom.helpers
    - r-cli
    - r-dplyr
    - r-forcats
    - r-ggplot2
    - r-lifecycle
    - r-magrittr
    - r-scales
    - r-tidyr

test:
  commands:
    - $R -e "library('ggstats')"           # [not win]
    - "\"%R%\" -e \"library('ggstats')\""  # [win]

about:
  home: https://larmarange.github.io/ggstats/
  dev_url: https://github.com/larmarange/ggstats/
  doc_url: https://larmarange.github.io/ggstats/reference/index.html
  license: GPL-3.0-only
  summary: Provides suite of functions to plot regression model coefficients ("forest plots"). The suite also includes new statistics to compute proportions, weighted mean and cross-tabulation statistics, as well as new geometries to add alternative background color to a plot.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
